### ISSUE TITLE
Bathtub Problem

### ISSUE THREAD

**Issue by RajarshiB21** [Unchained-RP/bugs#25]
Scrubbing while bathing does not remove dirt from the character

**Comment by LokidPhoenix** [comment]
This error cannot really be confirmed! I tried it in Valentine, and there it worked! 
here is the video of it!... But i will travel now around and test it!
https://medal.tv/games/red-dead-2/clips/jEPzKJ4L4QXds/d13372Px0Yga?invite=cr-MSxHQ2gsNTg3NzE0Mjcs

**Comment by NeonOdyssey** [comment]
This bug / issue has been fixed.

> @LokidPhoenix **said:**
> This error cannot really be confirmed! I tried it in Valentine, and there it worked! here is the video of it!... But i will travel now around and test it! https://medal.tv/games/red-dead-2/clips/jEPzKJ4L4QXds/d13372Px0Yga?invite=cr-MSxHQ2gsNTg3NzE0Mjcs
> 
> [EDIT] Checked now every Bath tub... Cleaning works in every of it.

If you still get this issue please wait until server restart.
After restart and you still get the issue please reopen!
