### ISSUE TITLE
A lot of the Breeding Settings do not work

### ISSUE THREAD

**Issue by CelinSilver** [Unchained-RP/bugs#28]
Settings file:
Horses are aging -> But ingame they do not
Horses do not get unfertile by breeding -> But ingame they do

Horses should breed in 30 min -> that works

**Comment by NeonOdyssey** [comment]
Baby horses do not age.

**Comment by Luke-Callaway** [comment]
horses take a little over 30 min to breed. arabian said 30 min to breed, couldnt collect the baby until 32 min. mustang collected at 34 as well as a baby shire. more data is being collected rn

**Comment by Luke-Callaway** [comment]
after 2 sets of 3 pairs, takes anywhere from 32-35 min

**Comment by NeonOdyssey** [comment]
> horses take a little over 30 min to breed. arabian said 30 min to breed, couldnt collect the baby until 32 min. mustang collected at 34 as well as a baby shire. more data is being collected rn

30 mins is only an estimate, as you cant tell exactly when a baby is going to be born
