### ISSUE TITLE
Annesburg Saloon Entry Exit problem

### ISSUE THREAD

**Issue by RajarshiB21** [Unchained-RP/bugs#29]
In the Annesburg Saloon with the  Moonshine Shack interior, there is an option to enter by hitting Enter however, once the person is inside there is no option to exit.

Entry:
https://cdn.discordapp.com/attachments/970389007978610738/970444425002094622/Annesburg_Saloon.png

Exit:
https://cdn.discordapp.com/attachments/970389007978610738/970444424586883082/Annesburg_Exit.png

**Comment by LokidPhoenix** [comment]
here is the exit of the annesburg saloon:
https://medal.tv/games/red-dead-2/clips/jHdhm6zwbrqcv/d1337TEMc5Ow?invite=cr-MSx2dTQsNTg3NzE0Mjcs

**Comment by UnchainedRP** [comment]
As stated above there is an exit to the saloons. tho i do not like the way the teleport is being run. I will change the system :)

**Comment by UnchainedRP** [comment]
Fixed. Used a different Teleport script :)
