### ISSUE TITLE
Wagon kicks you out immediately upon opening inventory.

### ISSUE THREAD

**Issue by Gjalahad** [Unchained-RP/bugs#32]
Naps do not work, Must wait for storm to be able to access your wagon. 
it happens to people randomly, and they have to wait till storm for it to be reset

Plays** a small Red dead Chime when the inventory is forcibly closed.

**Comment by NeonOdyssey** [comment]
Could you update this bug report as the title and description counteract eachother

**Comment by Gjalahad** [comment]
Also, Finding out that this glitch can be used to get unlimited items for free from this glitched inventory. Its possible to freeze this inventory when its meant to kick you out, but if you stay in this frozen menu and drag items out of the cart, it will actually come out into your inventory and stay in the cart so it ends up duplicating.

**Comment by LokidPhoenix** [comment]
It is still not fixed... I have this problem again, after i pulled my wagon out!
Inventory is still closing... and at some point, you can use it to duplicate items

**Comment by NeonOdyssey** [comment]
> It is still not fixed... I have this problem again, after i pulled my wagon out! Inventory is still closing... and at some point, you can use it to duplicate items

Can confirm this when entering someone's coach storage. Will open menu but close after 0.5 secconds

**Comment by McNextar** [comment]
https://youtu.be/mzwW8WBBvvI it happens at random times and only fixes after restart @NeonOdyssey 
https://github.com/Unchained-RP/bugs/issues/91 related

**Comment by McNextar** [comment]
Update it also causes you to lose items you manage to put in it if it freezes , i would know hour of mining gone

**Comment by UnchainedRP** [comment]
Fixed
