### ISSUE TITLE
Stawberry changing rooms

### ISSUE THREAD

**Issue by AnonymousGary** [Unchained-RP/bugs#35]
not accessible as door is locked
![20220502133809_1](https://user-images.githubusercontent.com/104747807/166181621-a9aca12f-3f71-4f89-8ae6-1463cd000073.jpg)

**Comment by UnchainedRP** [comment]
It is possible to acsess it from that side of the door but i will move the location.

**Comment by UnchainedRP** [comment]
It has been moved. Thakn you
