### ISSUE TITLE
Food Not Working

### ISSUE THREAD

**Issue by TheYetiB** [Unchained-RP/bugs#38]
When I go to eat food, it doesn't let me actually consume it or put it down. Goulash specifically.

**Comment by UnchainedRP** [comment]
Please can you provide more infomation? The item name would be helpful :)

**Comment by NeonOdyssey** [comment]
> Please can you provide more infomation? The item name would be helpful :)

I have also had this issue. I have to consume 2 food items or 2 drink items to make any mark on either hunger / thirst bar

**Comment by UnchainedRP** [comment]
> > Please can you provide more information? The item name would be helpful :)
> 
> I have also had this issue. I have to consume 2 food items or 2 drink items to make any mark on either hunger/thirst bar

This is not an issue with the food. this is an issue with the UI it works and registers but due to UI change it has created a minor "bug"
