### ISSUE TITLE
Calling horse

### ISSUE THREAD

**Issue by NeonOdyssey** [Unchained-RP/bugs#4]
When you try to call your horse when you have him out of the stable it won't come

From > James Hardy > RDR Rock#3338

**Comment by NeonOdyssey** [comment]
I've also encountered the bug where the horse does not respond to whistling regardless of the distance.

From > Dr. Mari Bartonelli (Tes) | Tes#0003

**Comment by AnonymousGary** [comment]
Me too

**Comment by UnchainedRP** [comment]
Up radius to 100 Should be fixed
