### ISSUE TITLE
Rhodes pullout

### ISSUE THREAD

**Issue by LokidPhoenix** [Unchained-RP/bugs#45]
At the Rhodes pullout station, you cant get your 4 horsed wagon out. It simply doens't spawn, and there is an notification:
![Screenshot_17](https://user-images.githubusercontent.com/20700785/166559136-88f7bfad-b895-4f10-836e-d4366f6f918b.png)

**Comment by NeonOdyssey** [comment]
Unfortunately  I am unable to reproduce this bug. 
Please make sure your horse has been selected in the stables and your horse is not already summoned. 
Please re-open if you still get this issue.

**Comment by NeonOdyssey** [comment]
Rhodes spawn location needs to be closer to a road node.
Black water spawn location needs to be rotated 90 deg (facing towards the road) as current location the 4 horse coaches are pressed up against the wall.
St Denis spawn location needs to be moved back (further in the alley) as 3 horse coach is almost pressed up against wall.

**Comment by LokidPhoenix** [comment]
St Denis Stable Icon, wrong Name^^ there is an "e" to much.
![Screenshot_18](https://user-images.githubusercontent.com/20700785/166583986-747defb5-2a5b-407d-ae0f-13d1b62f4aac.png)
