### ISSUE TITLE
Stable / Sell point in New Austin!

### ISSUE THREAD

**Issue by LucehOfficial** [Unchained-RP/bugs#46]
In all of NA there is no Sell point or actual Stable anywhere just a pull out point! which means if someone from NA would want to buy a horse/ sell one they would have to go to west Elizabeth instead :)

**Comment by NeonOdyssey** [comment]
This is not a bug!!
Please submit your suggestions into the [` #suggestions2 `](https://discord.com/channels/944656890040815667/970697361728880730) channel!!
