### ISSUE TITLE
Two of one item.

### ISSUE THREAD

**Issue by LilRedPandaa** [Unchained-RP/bugs#53]
After Bexar found out that Rhubarb gave you Burdock, he changed the Burdock to Burdock Root. Burdock Root was already an item before this, resulting in 2 different kinds of Burdock Root. One Burdock Root has a picture, the other doesn't. 
One Burdock Root says that it's a component for drugs and oils, while the other just says ask the natives.
I will be testing to see which one is used for Shaman stuff, but I believe it's the one with no picture.

**Comment by UnchainedRP** [comment]
No longer an issue. The item name is now true to what it should be. Rhubarb. (Also the image is fixed)
