### ISSUE TITLE
Keane Saloon locker not working

### ISSUE THREAD

**Issue by FarFetchedNews0207** [Unchained-RP/bugs#56]
My character, Stan Mann currently owns the saloon and he is not able to access the locker. I have tried different positions and cannot open the locker for myself. I also have the key to the property and have the respective job role for the saloon.

**Comment by UnchainedRP** [comment]
Is this still an issue?

**Comment by FarFetchedNews0207** [comment]
This is not a issue anymore. It fixed itself.
