### ISSUE TITLE
Horse Trainer bugg

### ISSUE THREAD

**Issue by TheJackForce** [Unchained-RP/bugs#58]
If you catch 2 wild horse at a time it will not allow you to save the second horse no script error just states cannot save

**Comment by LucehOfficial** [comment]
yeh the second horse despawns without anything, but i found a glitch in the matrix where you can get someone else to sit on the other horse and you can tame them both :)

**Comment by TheJackForce** [comment]
only the horse trainer tamed them and she could only save on not both

**Comment by LucehOfficial** [comment]
yeh after she tamed it, get someone else to sit on the other horse and then they can get off once the first one is tamed.

**Comment by TheJackForce** [comment]
we did that it didn't work

**Comment by LucehOfficial** [comment]
weird worked for me n lewis

**Comment by UnchainedRP** [comment]
Is this still an issue ?

**Comment by UnchainedRP** [comment]
Fixed
