### ISSUE TITLE
Saloon bartender items cost more than the store menu | Mint Tea does not work

### ISSUE THREAD

**Issue by FarFetchedNews0207** [Unchained-RP/bugs#59]
The bartender menu items cost more than the ones you can buy on the store menu. Because of this, it would be cheaper to just go to the store menu and buy drinks and such which would cause the saloon owners to lose out on money and RP. 

Bartender Menu:
Beer: $0.5
Good whiskey: $0.5
Bad Whiskey: $0.2
Wine: $0.3
Champagne Bottle: $.08
Coffee: $.07
Lemonade: $.02
Mint Tea: Does not work
Cigarettes:$0.1
Cigar: $0.2

Store Catalog:
Beer: $0.1
Good Whiskey: $0.3
Wine: $0.5
Coffee: $0.1
Lemonade: $0.4
Cigarettes: $0.03
Cigars: $0.4

I believe these prices need to be changed so that this will allow saloon owners to make a profit and not have other players go to the store menu and buy things outright. I am not saying the store menu needs to be removed but the prices need to increase while the bartender menu items need to be decreased. That way it would be cheaper to get a drink by doing RP. Comparable to going to a gunsmith... You will get a better deal from a gunsmith rather than their catalog. 

In addition, the mint tea does not work at all. The button is there but it does nothing.

**Comment by NeonOdyssey** [comment]
This is not a bug!
I will not delete this issue, however please either create a support ticket for this.
