### ISSUE TITLE
Downed animals disappear

### ISSUE THREAD

**Issue by TaliseManitou** [Unchained-RP/bugs#66]
Hunting today and the animals I shot disappear before I can get to them. I'll say out of 5 shot 3 vanish. Unsure why this is.

**Comment by NeonOdyssey** [comment]
> Hunting today and the animals I shot disappear before I can get to them. I'll say out of 5 shot 3 vanish. Unsure why this is.

unfortunately I am unable to reproduce this issue.
I have shot and killed 7 dear after going afk for 7 mins I could still see the animals on my minimap and did not disapear.
