### ISSUE TITLE
Drug Use

### ISSUE THREAD

**Issue by ButtersTheGimp** [Unchained-RP/bugs#69]
Drug consumption uses 2 instead of 1

**Comment by LokidPhoenix** [comment]
Please give more information? With wich drug did this error occur? 

So we can try to reproduce it and we can watch directly on the right sides in the code!

Thx

**Comment by CWilliams1211** [comment]
Error occurs with Cocaine, Opium and Morphine. Haven't tested Swamp Herb properly.
