### ISSUE TITLE
Tellegrams not working for me

### ISSUE THREAD

**Issue by Luke-Callaway** [Unchained-RP/bugs#73]
Dr mari bartonelli has recieved my tellegrams but ive recieved none of hers…? Not sure if its my end or hers, willing to test with other people to see if im not recieving tellegrams or not… for the mean time will people who want/need to send me a tellegram be able to dm me their rp tellegram via discord?

**Comment by NeonOdyssey** [comment]
# DO NOT send telegrams via discord

Discord is a form of OOC communication and this will be classed as meta gaming, and infractions will be dealt accordingly.
[Click here to check out the rules regarding metagaming](https://www.flipsnack.com/79DFBEFF8D6/unchained-rp-rulebook.html)

---
If the telegram system is down treat it as if the post office is closed. 
i.e use other means of communication, talk to people, use the public phones.
