### ISSUE TITLE
Can't see inventory icons

### ISSUE THREAD

**Issue by CWilliams1211** [Unchained-RP/bugs#77]
![image](https://user-images.githubusercontent.com/104893755/167773852-357d1d16-2ad7-46a2-8e74-1ad422366612.png)

![image](https://user-images.githubusercontent.com/104893755/167829305-ba1bcec6-f9f8-4304-b9d3-18d124c436d0.png)

**Comment by NeonOdyssey** [comment]
This was an issue with the gunsmith job.
We have resolved this and is now fully functional.
