### ISSUE TITLE
Horse training

### ISSUE THREAD

**Issue by LucehOfficial** [Unchained-RP/bugs#78]
Not sure if this has been said yet, but some peoples horses are going "Dumb" after being fully trained, ive been noticing this happening when you take out another horse the IQ transfers over to the new horse and bugs the old one and vise versa :)

**Comment by LucehOfficial** [comment]
![image](https://user-images.githubusercontent.com/104735994/167883251-abac1836-c787-44da-bfb6-c68abd7a093b.png)
This horse for example has taken the stats from the shire i just trained and this is meant to be at 195.

**Comment by Aichios** [comment]
Today I've encountered a variation of this. Instead, one fully trained horse lost all its training when I pulled another one out. The IQ didn't transfer, it just vanished.

**Comment by BeeGall** [comment]
I have encountered this issue as well. The moment I put away the horse and pull out a new one it forgets everything.

**Comment by UnchainedRP** [comment]
Fixed
