### ISSUE TITLE
Scuffed Pockets

### ISSUE THREAD

**Issue by Duckcommando** [Unchained-RP/bugs#80]
[A full description of the bug you are reporting]

### Steps to reproduce:
1. Open pockets
2. --
3. --

#### Current behaviour (bug)
Pockets are fucked.

#### Expected behaviour (correct)
Pockets arent fucked.

#### Images or video (optional)
https://imgur.com/ZZF9j9z
https://imgur.com/UJ34ffm

#### Reported by
Dr. Weatherford

**Comment by NeonOdyssey** [comment]
This bug / issue has been fixed.

If you still get this issue please relog into the server.
After restart and you still get the issue please reopen!
