### ISSUE TITLE
Wagon store locking up game

### ISSUE THREAD

**Issue by McNextar** [Unchained-RP/bugs#81]
when sorting through wagons in stable store , game will lock up and freeze , have already repeated issue by just changing wagons on bottom row

**Comment by McNextar** [comment]
update pressing backspace will get you out, butwagons then wont change or appear if you go back without a restart
https://youtu.be/_J0VMBsRcoA video recreation

**Comment by McNextar** [comment]
https://youtu.be/_J0VMBsRcoA

**Comment by NeonOdyssey** [comment]
This is a known issue when browsing through the worker wagons.
This can also cause the menu not to function the next time you open it. (you will have to re-log)

**Comment by UnchainedRP** [comment]
Fixed
