### ISSUE TITLE
Smelting short

### ISSUE THREAD

**Issue by McNextar** [Unchained-RP/bugs#87]
when smelting iron ore it keeps reverting back to a single iron plate, not the three its supposed to give, 2 iron ore= 1 iron plate should be 2 iron ore= 3 iron plates

**Comment by BigBartx13** [comment]
Neo. Investigate and action please. Try pull from test to main and restart to see if the fix sticks. Thanks

**Comment by McNextar** [comment]
also not sure if you did it yet be remember to make max iron ore to hold 30 and max iron plates
 125

**Comment by NeonOdyssey** [comment]
> Neo. Investigate and action please. Try pull from test to main and restart to see if the fix sticks. Thanks

no :) jk ❤️ 
ok daddy

**Comment by NeonOdyssey** [comment]
> 2 iron ore= 1 iron plate should be 2 iron ore= 3 iron plates

This has been fixed 

---
> when smelting iron ore it keeps reverting back to a single iron plate, not the three its supposed to give, 2 iron ore= 1 iron plate should be 2 iron ore= 3 iron plates

I think this has been fixed, I will test it and make sure
