### ISSUE TITLE
Making Pack of Cigarettes does not work

### ISSUE THREAD

**Issue by FarFetchedNews0207** [Unchained-RP/bugs#90]
I went and made a crafting table and had 27 tobacco and 10 wrapping paper. I went to craft 3 packs of cigarettes and all it did was take 21 tobacco and 6 wrapping paper and made 0 packs of cigarettes

### Steps to reproduce:
1. Use a crafting table that you made outside of a city
2. Right-click and produce any amount of packs of cigarettes

#### Current behaviour (bug)
You get no packs of cigarettes

#### Expected behaviour (correct)
You get packs of cigarettes

#### Reported by
Far#6451

**Comment by UnchainedRP** [comment]
We will look into this ASASP
