### ISSUE TITLE
Current Player HUD is over horse stats HUD

### ISSUE THREAD

**Issue by TaliseManitou** [Unchained-RP/bugs#95]
When on horseback the current player food/thirst HUD os almost directly on top of the horse's stam/health HUD. I have a photo but unsure how to attach it here

**Comment by TaliseManitou** [comment]
![bug](https://user-images.githubusercontent.com/105115702/172475352-aa582e00-7feb-49b7-bb8c-ed24eb68f87b.png)

**Comment by UnchainedRP** [comment]
#96 Merger

**Comment by UnchainedRP** [comment]
Fixed
