### ISSUE TITLE
Horse Breeding Testing

### ISSUE THREAD

**Issue by Lady-AllyKat** [Unchained-RP/bugs#98]
Started breeding 2 horses at 227am EST it is 317EST and the 120 timer has not progressed. Keeping an eye on it and updating you. Just trying to make sure its known

![RedM_b1436_GTAProcess_3zbURL1awG](https://user-images.githubusercontent.com/107391959/173300076-eddf8a07-787f-4c22-a64f-1562385435a4.jpg) 227AM EST

![RedM_b1436_GTAProcess_08QgmGE04u](https://user-images.githubusercontent.com/107391959/173300212-971eaf50-ac27-4382-be78-d73a8a4c1bf3.png)
 317AM EST

**Comment by Lady-AllyKat** [comment]
Update: now its 3pm EST, still no progress on the 2 horses breeding
![RedM_b1436_GTAProcess_qvliIh68eS](https://user-images.githubusercontent.com/107391959/173426025-44651303-5408-4304-8e71-9a7628c3d746.jpg)
.

**Comment by UnchainedRP** [comment]
Is this before or after your cub from last night ?

**Comment by Lady-AllyKat** [comment]
> Is this before or after your cub from last night ?

this was right prior the "horse health" restart

**Comment by UnchainedRP** [comment]
Gotcha. Ima close the ticket.
